spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gwangya
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
jwt:
  duration:
    access: 180
    refresh: 190