spring:
  datasource:
    url: jdbc:mysql://db-moj5l-kr.vpc-pub-cdb.ntruss.com:3306/gwangya
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
jwt:
  duration:
    access: 3600
    refresh: 259200
